//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cybertech_v1._1.EntityDataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Core_Modules_Functionality
    {
        public int id { get; set; }
        public Nullable<int> area_module_id { get; set; }
        public string module_action_name { get; set; }
    
        public virtual Core_Areas_Modules Core_Areas_Modules { get; set; }
    }
}
