//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cybertech_v1._1.EntityDataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Core_HeadCount
    {
        public int CSSL_ID { get; set; }
        public string Employee_Name { get; set; }
        public string Role { get; set; }
        public string Supervisor { get; set; }
        public string Type { get; set; }
        public string Technology { get; set; }
        public Nullable<System.DateTime> DOJ { get; set; }
        public string Team { get; set; }
        public string Active { get; set; }
        public Nullable<System.TimeSpan> Shift_Time { get; set; }
    }
}
