//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cybertech_v1._1.EntityDataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Core_LNK_Role_Module_Functionality
    {
        public int id { get; set; }
        public Nullable<int> role_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> module_id { get; set; }
        public Nullable<int> functionality_id { get; set; }
    
        public virtual Core_Areas_Modules Core_Areas_Modules { get; set; }
        public virtual Core_Roles Core_Roles { get; set; }
        public virtual Core_Users Core_Users { get; set; }
    }
}
