//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cybertech_v1._1.EntityDataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Core_Roles
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Core_Roles()
        {
            this.Core_LNK_Role_Module_Functionality = new HashSet<Core_LNK_Role_Module_Functionality>();
            this.Core_LNK_User_Role = new HashSet<Core_LNK_User_Role>();
        }
    
        public int role_id { get; set; }
        public string role_name { get; set; }
        public Nullable<int> sys_admin { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Core_LNK_Role_Module_Functionality> Core_LNK_Role_Module_Functionality { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Core_LNK_User_Role> Core_LNK_User_Role { get; set; }
    }
}
