//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cybertech_v1._1.EntityDataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Core_Areas_Modules
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Core_Areas_Modules()
        {
            this.Core_LNK_Role_Module_Functionality = new HashSet<Core_LNK_Role_Module_Functionality>();
            this.Core_Modules_Functionality = new HashSet<Core_Modules_Functionality>();
        }
    
        public int id { get; set; }
        public string moduleName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Core_LNK_Role_Module_Functionality> Core_LNK_Role_Module_Functionality { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Core_Modules_Functionality> Core_Modules_Functionality { get; set; }
    }
}
