//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cybertech_v1._1.EntityDataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profile_Work_Experiance
    {
        public long id { get; set; }
        public Nullable<int> user_id { get; set; }
        public string employer { get; set; }
        public string position { get; set; }
        public string principleactivity { get; set; }
        public string keyachievement { get; set; }
        public string startdate { get; set; }
        public string lastdate { get; set; }
    
        public virtual Core_Users Core_Users { get; set; }
    }
}
