//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cybertech_v1._1.EntityDataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Training_AttendanceLogs
    {
        public int Attendance_Id { get; set; }
        public Nullable<int> CSSL_ID { get; set; }
        public Nullable<System.DateTime> LoginDateTime { get; set; }
        public string Attendance_Status { get; set; }
        public string Remark { get; set; }
    }
}
